import { Router } from 'express'
import multer from 'multer'
import { query } from '../db/pool.js'
import { attachUser, requireAuth } from '../middleware/auth.js'
import { uploadToStorage } from '../services/storage.js'
import { resolveUploadCategory } from '../config/driveFolders.js'
import { queuePreviewGeneration } from '../services/previewQueue.js'
import { extractBasicMetadata } from '../utils/metadata.js'

const router = Router()

const ALLOWED_MIME_TYPES = new Set([
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'image/jpeg', 'image/png', 'image/webp',
  'audio/mpeg', 'audio/mp4', 'audio/wav',
  'video/mp4', 'video/webm',
  'application/zip', 'application/x-zip-compressed',
])

const MAX_FILE_SIZE_BYTES = 200 * 1024 * 1024

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: MAX_FILE_SIZE_BYTES },
  fileFilter: (req, file, cb) => {
    // Only enforce the allow-list on the actual resource file. The
    // client-rendered thumbnail always arrives as image/jpeg regardless
    // of the source document's type, so it must not be checked against
    // ALLOWED_MIME_TYPES (which is scoped to resource file types).
    if (file.fieldname === 'file' && !ALLOWED_MIME_TYPES.has(file.mimetype)) {
      return cb(new Error(`File type not allowed: ${file.mimetype}`))
    }
    if (file.fieldname === 'thumbnail' && !file.mimetype.startsWith('image/')) {
      return cb(new Error(`Thumbnail must be an image, got: ${file.mimetype}`))
    }
    cb(null, true)
  },
})

// Same intent as MultiFileUpload.jsx's client-side check — this is the
// server-side backstop for it. The client blanking the field is what
// normally prevents a hash from ever being typed in, but this endpoint
// can be hit directly (Postman, a future mobile client, retried requests
// with stale form state), so the title is never trusted blindly here
// either. Keep the two pattern lists in sync if either changes.
const AUTO_GENERATED_NAME_PATTERNS = [
  /^original[-_]?[0-9a-f]{16,}$/i,
  /^[0-9a-f]{16,}$/i,
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  /^(img|vid|video|audio|file|download|whatsapp|status|voice|rec)[-_ ]?\d{2,}$/i,
  /^\d{10,}$/,
]

function looksAutoGenerated(name) {
  const trimmed = String(name || '').trim()
  if (!trimmed) return false
  return AUTO_GENERATED_NAME_PATTERNS.some((re) => re.test(trimmed))
}

function humanizeSlug(slug) {
  return String(slug || 'resource')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

// Valid media_subtype values per resource type, enforced server-side so a
// direct API call can't write junk into a column the UI treats as an enum.
// Kept in one place so uploads.js and any future admin edit route agree.
const VALID_AUDIO_SUBTYPES = new Set(['single', 'panel'])
const VALID_VIDEO_SUBTYPES = new Set(['sermon', 'lecture', 'interview', 'recording', 'testimony', 'other'])

function resolveMediaSubtype(mimetype, rawValue) {
  const value = String(rawValue || '').trim().toLowerCase()
  if (!value) return null
  if (mimetype.startsWith('audio/')) return VALID_AUDIO_SUBTYPES.has(value) ? value : null
  if (mimetype.startsWith('video/')) return VALID_VIDEO_SUBTYPES.has(value) ? value : null
  return null
}

router.post(
  '/',
  attachUser,
  requireAuth,
  upload.fields([
    { name: 'file', maxCount: 1 },
    { name: 'thumbnail', maxCount: 1 }, // NEW — real client-rendered thumbnail (currently sent for DOCX)
  ]),
  async (req, res) => {
    const uploadedFile = req.files?.file?.[0]
    const uploadedThumbnail = req.files?.thumbnail?.[0]

    if (!uploadedFile) return res.status(400).json({ error: 'No file provided' })

    const {
      title, author, courseCode, description, resourceTypeSlug,
      categoryId, departmentId, level, semester, isAnonymous, mediaSubtype,
    } = req.body

    const typeResult = await query('SELECT id FROM resource_types WHERE slug = $1', [resourceTypeSlug])
    if (typeResult.rows.length === 0) return res.status(400).json({ error: 'Invalid resource type' })

    const basicMetadata = await extractBasicMetadata(uploadedFile)

    // Uploader-provided values always win — but only if they don't look like
    // machine-generated junk. A hash/UUID/camera-default filename is never
    // an acceptable title, no matter which source it came from (typed,
    // detected, or the raw filename) — it falls through to the next source,
    // and ultimately to a plain "Untitled <Type>" rather than ever showing
    // a raw hash to a reader.
    const typedTitle = title?.trim() && !looksAutoGenerated(title.trim()) ? title.trim() : null
    const detectedTitle = basicMetadata.detectedTitle && !looksAutoGenerated(basicMetadata.detectedTitle) ? basicMetadata.detectedTitle : null
    const rawFilenameTitle = uploadedFile.originalname.replace(/\.[^./\\]+$/, '')
    const filenameTitle = looksAutoGenerated(rawFilenameTitle) ? null : rawFilenameTitle

    const finalTitle = typedTitle || detectedTitle || filenameTitle || `Untitled ${humanizeSlug(resourceTypeSlug)}`
    const finalAuthor = author?.trim() || basicMetadata.detectedAuthor || null
    const finalMediaSubtype = resolveMediaSubtype(uploadedFile.mimetype, mediaSubtype)

    // FormData sends booleans as the strings "true"/"false", not real
    // booleans — checked explicitly here rather than relying on truthiness.
    const anonymous = isAnonymous === 'true' || isAnonymous === true

    const driveCategory = resolveUploadCategory({ mimetype: uploadedFile.mimetype, resourceTypeSlug })
    const stored = await uploadToStorage(uploadedFile, driveCategory)

    // Upload the real client-rendered thumbnail (if one was sent) right
    // away, before insert, so previewQueue.js can use it immediately
    // instead of attempting server-side generation that's known to fail
    // for DOCX/PPT (see previewFromOffice stub) and falling back to the
    // generated cover card.
    let clientThumbnail = null
    if (uploadedThumbnail) {
      const storedThumbnail = await uploadToStorage(uploadedThumbnail, 'img', { makePublic: true })
      clientThumbnail = { fileId: storedThumbnail.fileId }
    }

    const inserted = await query(
      `INSERT INTO resources (
         title, author, description, course_code, department_id, category_id,
         resource_type_id, level, semester,
         storage_provider, file_id, file_url, file_name, file_type, file_size_bytes,
         width_px, height_px, aspect_ratio,
         uploaded_by, is_anonymous, thumbnail_status, media_subtype
       ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,'pending',$21)
       RETURNING id`,
      [
        finalTitle, finalAuthor, description || null, courseCode || null,
        departmentId || null, categoryId || null, typeResult.rows[0].id, level || null, semester || null,
        stored.provider, stored.fileId, stored.fileUrl, uploadedFile.originalname, uploadedFile.mimetype, uploadedFile.size,
        basicMetadata.widthPx, basicMetadata.heightPx, basicMetadata.aspectRatio,
        req.user.id, anonymous, finalMediaSubtype,
      ]
    )

    const resourceId = inserted.rows[0].id

    // Passing uploadedFile.buffer directly means PDF page-1 rendering doesn't
    // need to re-download the file from Drive — it renders straight from
    // the upload already sitting in memory.
    queuePreviewGeneration(resourceId, stored, uploadedFile.mimetype, uploadedFile.buffer, clientThumbnail)

    res.status(201).json({
      resourceId,
      status: 'pending_review',
      detectedAuthor: !author?.trim() ? basicMetadata.detectedAuthor : null,
    })
  }
)

export default router