import { Router } from 'express'
import multer from 'multer'
import { query } from '../db/pool.js'
import { attachUser, requireAuth } from '../middleware/auth.js'
import { uploadToStorage } from '../services/storage.js'
import { resolveUploadCategory } from '../config/driveFolders.js'
import { queuePreviewGeneration } from '../services/previewQueue.js'
import { extractBasicMetadata } from '../utils/metadata.js'

const router = Router()

const ALLOWED_MIME_TYPES = new Set([
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'image/jpeg', 'image/png', 'image/webp',
  'audio/mpeg', 'audio/mp4', 'audio/wav',
  'video/mp4', 'video/webm',
  'application/zip', 'application/x-zip-compressed',
])

const MAX_FILE_SIZE_BYTES = 200 * 1024 * 1024

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: MAX_FILE_SIZE_BYTES },
  fileFilter: (req, file, cb) => {
    if (!ALLOWED_MIME_TYPES.has(file.mimetype)) {
      return cb(new Error(`File type not allowed: ${file.mimetype}`))
    }
    cb(null, true)
  },
})

// Same intent as MultiFileUpload.jsx's client-side check — this is the
// server-side backstop for it. The client blanking the field is what
// normally prevents a hash from ever being typed in, but this endpoint
// can be hit directly (Postman, a future mobile client, retried requests
// with stale form state), so the title is never trusted blindly here
// either. Keep the two pattern lists in sync if either changes.
const AUTO_GENERATED_NAME_PATTERNS = [
  /^original[-_]?[0-9a-f]{16,}$/i,
  /^[0-9a-f]{16,}$/i,
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  /^(img|vid|video|audio|file|download|whatsapp|status|voice|rec)[-_ ]?\d{2,}$/i,
  /^\d{10,}$/,
]

function looksAutoGenerated(name) {
  const trimmed = String(name || '').trim()
  if (!trimmed) return false
  return AUTO_GENERATED_NAME_PATTERNS.some((re) => re.test(trimmed))
}

function humanizeSlug(slug) {
  return String(slug || 'resource')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

// Valid media_subtype values per resource type, enforced server-side so a
// direct API call can't write junk into a column the UI treats as an enum.
// Kept in one place so uploads.js and any future admin edit route agree.
const VALID_AUDIO_SUBTYPES = new Set(['single', 'panel'])
const VALID_VIDEO_SUBTYPES = new Set(['sermon', 'lecture', 'interview', 'recording', 'testimony', 'other'])

function resolveMediaSubtype(mimetype, rawValue) {
  const value = String(rawValue || '').trim().toLowerCase()
  if (!value) return null
  if (mimetype.startsWith('audio/')) return VALID_AUDIO_SUBTYPES.has(value) ? value : null
  if (mimetype.startsWith('video/')) return VALID_VIDEO_SUBTYPES.has(value) ? value : null
  return null
}

router.post('/', attachUser, requireAuth, upload.single('file'), async (req, res) => {
  if (!req.file) return res.status(400).json({ error: 'No file provided' })

  const {
    title, author, courseCode, description, resourceTypeSlug,
    categoryId, departmentId, level, semester, isAnonymous, mediaSubtype,
  } = req.body

  const typeResult = await query('SELECT id FROM resource_types WHERE slug = $1', [resourceTypeSlug])
  if (typeResult.rows.length === 0) return res.status(400).json({ error: 'Invalid resource type' })

  const basicMetadata = await extractBasicMetadata(req.file)

  // Uploader-provided values always win — but only if they don't look like
  // machine-generated junk. A hash/UUID/camera-default filename is never
  // an acceptable title, no matter which source it came from (typed,
  // detected, or the raw filename) — it falls through to the next source,
  // and ultimately to a plain "Untitled <Type>" rather than ever showing
  // a raw hash to a reader.
  const typedTitle = title?.trim() && !looksAutoGenerated(title.trim()) ? title.trim() : null
  const detectedTitle = basicMetadata.detectedTitle && !looksAutoGenerated(basicMetadata.detectedTitle) ? basicMetadata.detectedTitle : null
  const rawFilenameTitle = req.file.originalname.replace(/\.[^./\\]+$/, '')
  const filenameTitle = looksAutoGenerated(rawFilenameTitle) ? null : rawFilenameTitle

  const finalTitle = typedTitle || detectedTitle || filenameTitle || `Untitled ${humanizeSlug(resourceTypeSlug)}`
  const finalAuthor = author?.trim() || basicMetadata.detectedAuthor || null
  const finalMediaSubtype = resolveMediaSubtype(req.file.mimetype, mediaSubtype)

  // FormData sends booleans as the strings "true"/"false", not real
  // booleans — checked explicitly here rather than relying on truthiness.
  const anonymous = isAnonymous === 'true' || isAnonymous === true

  const driveCategory = resolveUploadCategory({ mimetype: req.file.mimetype, resourceTypeSlug })
  const stored = await uploadToStorage(req.file, driveCategory)

  const inserted = await query(
    `INSERT INTO resources (
       title, author, description, course_code, department_id, category_id,
       resource_type_id, level, semester,
       storage_provider, file_id, file_url, file_name, file_type, file_size_bytes,
       width_px, height_px, aspect_ratio,
       uploaded_by, is_anonymous, thumbnail_status, media_subtype
     ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,'pending',$21)
     RETURNING id`,
    [
      finalTitle, finalAuthor, description || null, courseCode || null,
      departmentId || null, categoryId || null, typeResult.rows[0].id, level || null, semester || null,
      stored.provider, stored.fileId, stored.fileUrl, req.file.originalname, req.file.mimetype, req.file.size,
      basicMetadata.widthPx, basicMetadata.heightPx, basicMetadata.aspectRatio,
      req.user.id, anonymous, finalMediaSubtype,
    ]
  )

  const resourceId = inserted.rows[0].id

  // Passing req.file.buffer directly means PDF page-1 rendering doesn't
  // need to re-download the file from Drive — it renders straight from
  // the upload already sitting in memory.
  queuePreviewGeneration(resourceId, stored, req.file.mimetype, req.file.buffer)

  res.status(201).json({
    resourceId,
    status: 'pending_review',
    detectedAuthor: !author?.trim() ? basicMetadata.detectedAuthor : null,
  })
})

export default router